#define GFX_drawLine AA_ST7735_drawLine
#define GFX_drawRect AA_ST7735_drawRect 

#define GFX_drawCircle AA_ST7735_drawCircle
#define GFX_drawCircleHelper AA_ST7735_drawCircleHelper

#define GFX_fillCircle AA_ST7735_fillCircle
#define GFX_fillCircleHelper AA_ST7735_fillCircleHelper


#define GFX_drawRoundRect AA_ST7735_drawRoundRect
#define GFX_fillRoundRect AA_ST7735_fillRoundRect

#define GFX_drawTriangle AA_ST7735_drawTriangle
#define GFX_fillTriangle AA_ST7735_fillTriangle

#define GFX_drawBitmapT AA_ST7735_drawBitmapT
#define GFX_drawBitmapBG AA_ST7735_drawBitmapBG

#define GFX_drawXBitmapT AA_ST7735_drawXBitmapT
#define GFX_drawXBitmapBG AA_ST7735_drawXBitmapBG

#define GFX_drawChar AA_ST7735_drawChar
#define GFX_setCursor AA_ST7735_setCursor

#define GFX_rawImgFromFile AA_ST7735_rawImgFromFile
#define GFX_rawImgFromFH AA_ST7735_rawImgFromFH
#define GFX_rawImgFromSpack AA_ST7735_GFX_rawImgFromSpack
