#define GFX_drawLine Adafruit_ST7735_drawLine
#define GFX_drawRect Adafruit_ST7735_drawRect 

#define GFX_drawCircle Adafruit_ST7735_drawCircle
#define GFX_drawCircleHelper Adafruit_ST7735_drawCircleHelper

#define GFX_fillCircle Adafruit_ST7735_fillCircle
#define GFX_fillCircleHelper Adafruit_ST7735_fillCircleHelper


#define GFX_drawRoundRect Adafruit_ST7735_drawRoundRect
#define GFX_fillRoundRect Adafruit_ST7735_fillRoundRect

#define GFX_drawTriangle Adafruit_ST7735_drawTriangle
#define GFX_fillTriangle Adafruit_ST7735_fillTriangle

#define GFX_drawBitmapT Adafruit_ST7735_drawBitmapT
#define GFX_drawBitmapBG Adafruit_ST7735_drawBitmapBG

#define GFX_drawXBitmapT Adafruit_ST7735_drawXBitmapT
#define GFX_drawXBitmapBG Adafruit_ST7735_drawXBitmapBG
